name: 'Setup QMK firmware'

inputs:
  version:
    default: '0.22.3'
    type: string
    required: false
  path:
    default: '__qmk__'
    type: string
    required: false
  avrgcc_version:
    default: '8.3.0'
    type: string
    required: false

runs:
  using: 'composite'
  steps:

  - name: Install git and pip
    shell: bash
    run: sudo apt-get install -y git python3-pip libfl2

  - name: Install QMK CLI
    shell: bash
    run: python3 -m pip install --user qmk

  - name: Checkout qmk_firmware
    uses: actions/checkout@v4
    with:
      path: ${{ inputs.path }}
      repository: qmk/qmk_firmware
      submodules: recursive
      ref: ${{ inputs.version }}

  - name: Setup QMK
    shell: bash
    run: qmk setup --home ${{ inputs.path }} --yes

  - name: Install newer gcc-avr
    shell: bash
    run: |
      # use https://github.com/ZakKemble/avr-gcc-build instead of default
      wget -q --show-progress --progress=bar:force https://github.com/ZakKemble/avr-gcc-build/releases/download/v${{ inputs.avrgcc_version }}-1/avr-gcc-${{ inputs.avrgcc_version }}-x64-linux.tar.bz2 -O /tmp/avrgcc.tar.bz2
      sudo tar xjf /tmp/avrgcc.tar.bz2 --strip-components=1 -C /usr/
      rm -f /tmp/avrgcc.tar.bz2
      avr-gcc --version
